services:
  banco-dados:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=api_produtos

  simulador-aws:
    image: localstack/localstack
    ports:
      - 4566:4566 # LocalStack Gateway
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}

  cache:
    image: redis
    environment:
      - REDIS_ARGS=--requirepass senha-redis --appendonly yes

  rastreamento-tracing:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem

  mensageria:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: coelho-lapin
      RABBITMQ_DEFAULT_PASS: coelho-lapin
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins

  api:
    image: api-produto
    depends_on:
      - banco-dados
      - simulador-aws
      - cache
      - rastreamento-tracing
      - mensageria

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
