# AWS
spring.cloud.aws.endpoint=http://simulador-aws:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# AWS_S3
aws.s3.bucket.name=local-bucket
spring.cloud.aws.s3.path-style-access-enabled=true

# DB
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://banco-dados:5432/api_produtos
spring.datasource.username=admin
spring.datasource.password=secret

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:/db/migrations

# JPA
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=false

# RabbitMQ
spring.rabbitmq.host=mensageria
spring.rabbitmq.port=5672
spring.rabbitmq.username=coelho-lapin
spring.rabbitmq.password=coelho-lapin

# Redis
spring.data.redis.host=cache
spring.data.redis.port=6379

# Tracing
management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=w3c
management.tracing.baggage.enabled=true
management.tracing.export.zipkin.enabled=true
management.tracing.export.zipkin.endpoint=http://rastreamento-tracing:9411/api/v2/spans